### ISSUE TITLE
`extern crate` is unnecessary with Rust 2018

### ISSUE THREAD

**Issue by hazel-ocean** [akrantz01/vssh#1]
Just taking a look the project. As of Rust 2018 edition, `extern crate` is typically unnecessary unless you're trying to `#[macro_use]`. Take a look at [the 2018 edition guide](https://doc.rust-lang.org/nightly/edition-guide/rust-2018/module-system/path-clarity.html?highlight=extern#no-more-extern-crate) to learn more 😄

**Comment by akrantz01** [comment]
Good to know, thanks!
