### ISSUE TITLE
Possible simplification with `thiserror`

### ISSUE THREAD

**Issue by hazel-ocean** [akrantz01/vssh#2]
It might be possible to simplify your errors somewhat by bringing in [thiserror](https://docs.rs/thiserror/1.0.11/thiserror/). It automates implementing `Display` and `From` traits pretty cleanly, and can be paired with `anyhow` (if you wanted). It's not necessary, but might remove some lines of code and seems to be pretty idiomatic currently in the community.

**Comment by akrantz01** [comment]
Thanks for the suggestion of the `thiserror` crate, it's really useful. I'll look into using `anyhow` in the near future.
