### ISSUE TITLE
Config::read should take &Path

### ISSUE THREAD

**Issue by hazel-ocean** [akrantz01/vssh#3]
`Config::read` should take a `&Path` instead of a `String`. The reason for that is that some filesystems aren't limited to only stored file paths as Unicode compliant Strings. That's really the main reason that `Path`, `PathBuf`, as well as `OsStr` and `OsString` exist - to catch those edge cases where you can have a file or directory named something outside of what would be valid Unicode codepoints.

**Comment by akrantz01** [comment]
I just fixed it. I hadn't considered that, thanks for the insight.
